### ISSUE TITLE
apollo_admin task not executed at the right time

### ISSUE THREAD

**Issue by nathandunn** [erasche/docker-compose-galaxy-annotation#1]
I have to do:

   docker-compose up apollo_admin 

after the first load.  This could be timed better, added as a dependent task, or just added to the ```apollo-config.groovy``` 

Not super-high priority as only has to be run once, but good to have.

**Comment by erasche** [comment]
Would love to have this part of apollo's config.

That way I would feel "safer" spinning up an apollo instance that is publicly accessible, lest someone else get to the "admin resgister" screen before I do.

**Comment by nathandunn** [comment]
Okay . . I can add that, the downside is that we have to have a "master" build of apollo (as opposed to 2.0.2).   Added here: https://github.com/GMOD/Apollo/issues/1040

**Comment by erasche** [comment]
Sure, that's probably ok? As long as people know they should be on versioned releases instead of just the `:latest/:master` image tag

**Comment by nathandunn** [comment]
My only worry is that 2.0.2 is very well tested and 2.0.3 while almost done hasn't gone through the same level of testing.   So, I think we can just create documentation (what I am doing now) that indicates that you have to do it, but eventually you won't.

**Comment by nathandunn** [comment]
But I'll try to see how stable it is for the purposes of this . . . I think that this is lower priority than #2 and getting the proper organism / strain stuff out the door.

**Comment by erasche** [comment]
> very well tested and 2.0.3 while almost done hasn't gone through the same level of testing

Just out of curiosity, are there some low-hanging fruit for automation there? I tend to discount any tests that aren't run regularly as part of a build process.

**Comment by nathandunn** [comment]
We run a full suite of tests:

https://travis-ci.org/GMOD/Apollo <https://travis-ci.org/GMOD/Apollo>

**Comment by erasche** [comment]
Sure, of course.

"Same level of testing" implied that there were tests run against releases which in-dev work was not subject to.

**Comment by nathandunn** [comment]
Yep.  There are just a lot of details, but since we are a work in progress it should be fine.   Let me get some of the basics working and then I can come back to this.

**Comment by erasche** [comment]
Sure. works for me.
