### ISSUE TITLE
remove / configure so that phage  / strain don't show on startup

### ISSUE THREAD

**Issue by nathandunn** [erasche/docker-compose-galaxy-annotation#2]
Wasn't sure if there was a way to do this at the top-level so that we could have appropriate sub-levels to do this with (i.e,. can we keep the original configuration / tools files if its convenient for you and add additional changes if not).

**Comment by erasche** [comment]
My org's copy of the tools can lag behind the "official" version. Happy to strip everything phage related.

**Comment by nathandunn** [comment]
thanks
