### ISSUE TITLE
library/agx not found

### ISSUE THREAD

**Issue by nathandunn** [erasche/docker-compose-galaxy-annotation#4]
https://github.com/erasche/docker-compose-galaxy-annotation/blob/master/docker-compose.yml#L14

@erasche  I may have pulled this too soon.  Let me know.

**Comment by erasche** [comment]
Whoops. That shouldn't've been committed.

**Comment by nathandunn** [comment]
Also getting this:

```
Pulling repository docker.io/library/apollo
ERROR: Error: image library/apollo not found
nathandunn:docker-compose-galaxy-annotation% 
```

**Comment by erasche** [comment]
Yep, should be fixed if you re-pull. Sorry those are names of images I was testing locally.

**Comment by nathandunn** [comment]
Seems to work.  Has the entry point changed?

nathandunn:docker-compose-galaxy-annotation% docker-compose ps 
                  Name                                 Command               State                 Ports                
-----------------------------------------------------------------------------------------------------------------------
dockercomposegalaxyannotation_apollo_1      catalina.sh run                  Up      8080/tcp                           
dockercomposegalaxyannotation_apollo_db_1   /docker-entrypoint.sh postgres   Up      5432/tcp                           
dockercomposegalaxyannotation_chado_1       /docker-entrypoint.sh postgres   Up      5432/tcp                           
dockercomposegalaxyannotation_galaxy_1      /usr/bin/startup                 Up      21/tcp, 80/tcp, 8800/tcp, 9002/tcp 
dockercomposegalaxyannotation_proxy_1       nginx -g daemon off;             Up      443/tcp, 0.0.0.0:8080->80/tcp      
dockercomposegalaxyannotation_tripal_1      /entrypoint.sh                   Up      80/tcp          


Apollo comes up on :8080/apollo

but galaxy nor tripal is coming up on port :80/

Any ideas? 

Nathan

**Comment by erasche** [comment]
@nathandunn sorry, I hardcoded the port whilst testing tripal (because drupal? Ugh). 

Galaxy will come up on `:8080/`, tripal (someday) will come up on `:8080/tripal`.

I'll move the tripal testing into another branch since it's a bloody mess.

**Comment by erasche** [comment]
209daf7ab4e511a2233f76ead65e1661449def33 moves everything back to the random (easy for deployers to use) port. Additionally removes tripal due to multitude of issues with it.

**Comment by nathandunn** [comment]
Alright .. Will test on Monday.

Nathan
